# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QSplitter,
    QStatusBar, QTextEdit, QTreeView, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1000, 618)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"C:/Users/john/.designer/backup/resources/icons/mast.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.fileNew = QAction(MainWindow)
        self.fileNew.setObjectName(u"fileNew")
        icon1 = QIcon()
        icon1.addFile(u"resources/icons/fileNew.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileNew.setIcon(icon1)
        self.fileNewWindow = QAction(MainWindow)
        self.fileNewWindow.setObjectName(u"fileNewWindow")
        icon2 = QIcon()
        icon2.addFile(u"resources/icons/fileNewWindow.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileNewWindow.setIcon(icon2)
        self.fileOpen = QAction(MainWindow)
        self.fileOpen.setObjectName(u"fileOpen")
        icon3 = QIcon()
        icon3.addFile(u"resources/icons/fileOpen.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileOpen.setIcon(icon3)
        self.fileOpenFolder = QAction(MainWindow)
        self.fileOpenFolder.setObjectName(u"fileOpenFolder")
        icon4 = QIcon()
        icon4.addFile(u"resources/icons/fileOpenFolder.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileOpenFolder.setIcon(icon4)
        self.fileOpenRecent = QAction(MainWindow)
        self.fileOpenRecent.setObjectName(u"fileOpenRecent")
        icon5 = QIcon()
        icon5.addFile(u"resources/icons/fileOpenRecent.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileOpenRecent.setIcon(icon5)
        self.fileSave = QAction(MainWindow)
        self.fileSave.setObjectName(u"fileSave")
        icon6 = QIcon()
        icon6.addFile(u"resources/icons/fileSave.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileSave.setIcon(icon6)
        self.fileSaveAs = QAction(MainWindow)
        self.fileSaveAs.setObjectName(u"fileSaveAs")
        icon7 = QIcon()
        icon7.addFile(u"resources/icons/fileSaveAs.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileSaveAs.setIcon(icon7)
        self.fileMoveTo = QAction(MainWindow)
        self.fileMoveTo.setObjectName(u"fileMoveTo")
        icon8 = QIcon()
        icon8.addFile(u"resources/icons/fileMoveTo.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.fileMoveTo.setIcon(icon8)
        self.actionSave_All = QAction(MainWindow)
        self.actionSave_All.setObjectName(u"actionSave_All")
        self.editUndo = QAction(MainWindow)
        self.editUndo.setObjectName(u"editUndo")
        icon9 = QIcon()
        icon9.addFile(u"resources/icons/editUndo.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editUndo.setIcon(icon9)
        self.editRedo = QAction(MainWindow)
        self.editRedo.setObjectName(u"editRedo")
        icon10 = QIcon()
        icon10.addFile(u"resources/icons/editRedo.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editRedo.setIcon(icon10)
        self.editCut = QAction(MainWindow)
        self.editCut.setObjectName(u"editCut")
        icon11 = QIcon()
        icon11.addFile(u"resources/icons/editCut.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editCut.setIcon(icon11)
        self.editCopy = QAction(MainWindow)
        self.editCopy.setObjectName(u"editCopy")
        icon12 = QIcon()
        icon12.addFile(u"resources/icons/editCopy.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editCopy.setIcon(icon12)
        self.editPaste = QAction(MainWindow)
        self.editPaste.setObjectName(u"editPaste")
        icon13 = QIcon()
        icon13.addFile(u"resources/icons/editPaste.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editPaste.setIcon(icon13)
        self.editSelectAll = QAction(MainWindow)
        self.editSelectAll.setObjectName(u"editSelectAll")
        icon14 = QIcon()
        icon14.addFile(u"resources/icons/editSelectAll.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editSelectAll.setIcon(icon14)
        self.editJumpToTop = QAction(MainWindow)
        self.editJumpToTop.setObjectName(u"editJumpToTop")
        self.editJumpToSelection = QAction(MainWindow)
        self.editJumpToSelection.setObjectName(u"editJumpToSelection")
        self.editJumpToBottom = QAction(MainWindow)
        self.editJumpToBottom.setObjectName(u"editJumpToBottom")
        self.editJumpToLineStart = QAction(MainWindow)
        self.editJumpToLineStart.setObjectName(u"editJumpToLineStart")
        self.editJumpToLineEnd = QAction(MainWindow)
        self.editJumpToLineEnd.setObjectName(u"editJumpToLineEnd")
        self.actionFind_and_Replace = QAction(MainWindow)
        self.actionFind_and_Replace.setObjectName(u"actionFind_and_Replace")
        self.editFind = QAction(MainWindow)
        self.editFind.setObjectName(u"editFind")
        icon15 = QIcon()
        icon15.addFile(u"resources/icons/editFind.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editFind.setIcon(icon15)
        self.editFindNext = QAction(MainWindow)
        self.editFindNext.setObjectName(u"editFindNext")
        self.editFindPrevious = QAction(MainWindow)
        self.editFindPrevious.setObjectName(u"editFindPrevious")
        self.editReplace = QAction(MainWindow)
        self.editReplace.setObjectName(u"editReplace")
        icon16 = QIcon()
        icon16.addFile(u"resources/icons/editReplace.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.editReplace.setIcon(icon16)
        self.helpAbout = QAction(MainWindow)
        self.helpAbout.setObjectName(u"helpAbout")
        icon17 = QIcon()
        icon17.addFile(u"resources/icons/helpAbout.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.helpAbout.setIcon(icon17)
        self.compileLaTeX = QAction(MainWindow)
        self.compileLaTeX.setObjectName(u"compileLaTeX")
        icon18 = QIcon()
        icon18.addFile(u"resources/icons/compileLaTeX.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.compileLaTeX.setIcon(icon18)
        self.compileTypst = QAction(MainWindow)
        self.compileTypst.setObjectName(u"compileTypst")
        icon19 = QIcon()
        icon19.addFile(u"resources/icons/compileTypst.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.compileTypst.setIcon(icon19)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.treeView = QTreeView(self.splitter)
        self.treeView.setObjectName(u"treeView")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy1)
        self.treeView.setMinimumSize(QSize(0, 0))
        self.treeView.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        self.treeView.setFont(font)
        self.treeView.setFrameShape(QFrame.NoFrame)
        self.treeView.setFrameShadow(QFrame.Plain)
        self.treeView.setLineWidth(0)
        self.treeView.setAutoScrollMargin(16)
        self.splitter.addWidget(self.treeView)
        self.textEdit = QTextEdit(self.splitter)
        self.textEdit.setObjectName(u"textEdit")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy2)
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(12)
        self.textEdit.setFont(font1)
        self.textEdit.setFrameShape(QFrame.NoFrame)
        self.textEdit.setLineWidth(0)
        self.textEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.splitter.addWidget(self.textEdit)
        self.webEngineView = QWebEngineView(self.splitter)
        self.webEngineView.setObjectName(u"webEngineView")
        self.webEngineView.setUrl(QUrl(u"about:blank"))
        self.splitter.addWidget(self.webEngineView)

        self.verticalLayout.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSelection = QMenu(self.menuEdit)
        self.menuSelection.setObjectName(u"menuSelection")
        self.menuFindAndReplace = QMenu(self.menuEdit)
        self.menuFindAndReplace.setObjectName(u"menuFindAndReplace")
        self.menuCompile = QMenu(self.menubar)
        self.menuCompile.setObjectName(u"menuCompile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCompile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.fileNew)
        self.menuFile.addAction(self.fileNewWindow)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.fileOpen)
        self.menuFile.addAction(self.fileOpenFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.fileOpenRecent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.fileSave)
        self.menuFile.addAction(self.fileSaveAs)
        self.menuFile.addAction(self.fileMoveTo)
        self.menuEdit.addAction(self.editUndo)
        self.menuEdit.addAction(self.editRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.editCut)
        self.menuEdit.addAction(self.editCopy)
        self.menuEdit.addAction(self.editPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuSelection.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuFindAndReplace.menuAction())
        self.menuSelection.addAction(self.editSelectAll)
        self.menuSelection.addSeparator()
        self.menuSelection.addAction(self.editJumpToTop)
        self.menuSelection.addAction(self.editJumpToSelection)
        self.menuSelection.addAction(self.editJumpToBottom)
        self.menuSelection.addSeparator()
        self.menuSelection.addAction(self.editJumpToLineStart)
        self.menuSelection.addAction(self.editJumpToLineEnd)
        self.menuSelection.addSeparator()
        self.menuFindAndReplace.addAction(self.editFind)
        self.menuFindAndReplace.addAction(self.editFindNext)
        self.menuFindAndReplace.addAction(self.editFindPrevious)
        self.menuFindAndReplace.addSeparator()
        self.menuFindAndReplace.addAction(self.editReplace)
        self.menuCompile.addAction(self.compileLaTeX)
        self.menuCompile.addAction(self.compileTypst)
        self.menuHelp.addAction(self.helpAbout)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Mast", None))
        self.fileNew.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
#if QT_CONFIG(tooltip)
        self.fileNew.setToolTip(QCoreApplication.translate("MainWindow", u"\u521b\u5efa\u4e00\u4e2a\u65b0\u7684\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.fileNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.fileNewWindow.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u7a97\u53e3", None))
        self.fileNewWindow.setIconText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u7a97\u53e3", None))
#if QT_CONFIG(tooltip)
        self.fileNewWindow.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u4e00\u4e2a\u65b0\u7684\u7a97\u53e3", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.fileNewWindow.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+N", None))
#endif // QT_CONFIG(shortcut)
        self.fileOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
#if QT_CONFIG(tooltip)
        self.fileOpen.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6307\u5b9a\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.fileOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.fileOpenFolder.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6\u5939", None))
#if QT_CONFIG(tooltip)
        self.fileOpenFolder.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u4e00\u4e2a\u6307\u5b9a\u7684\u6587\u4ef6\u5939", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.fileOpenFolder.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.fileOpenRecent.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6700\u8fd1\u6587\u4ef6", None))
        self.fileSave.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(tooltip)
        self.fileSave.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6\u66f4\u6539\u6216\u521b\u5efa\u4e00\u4e2a\u65b0\u7684\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.fileSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.fileSaveAs.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#if QT_CONFIG(tooltip)
        self.fileSaveAs.setToolTip(QCoreApplication.translate("MainWindow", u"\u5c06\u6587\u4ef6\u53e6\u5b58\u5230\u6307\u5b9a\u8def\u5f84\u6216\u6307\u5b9a\u683c\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.fileSaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.fileMoveTo.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u52a8\u5230", None))
#if QT_CONFIG(tooltip)
        self.fileMoveTo.setToolTip(QCoreApplication.translate("MainWindow", u"\u5c06\u6587\u4ef6\u79fb\u52a8\u5230\u6307\u5b9a\u7684\u4f4d\u7f6e", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave_All.setText(QCoreApplication.translate("MainWindow", u"Save All", None))
        self.editUndo.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#if QT_CONFIG(tooltip)
        self.editUndo.setToolTip(QCoreApplication.translate("MainWindow", u"\u64a4\u9500\u4e0a\u4e00\u6b21\u64cd\u4f5c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.editUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.editRedo.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#if QT_CONFIG(tooltip)
        self.editRedo.setToolTip(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u4e0a\u4e00\u6b21\u64cd\u4f5c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.editRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.editCut.setText(QCoreApplication.translate("MainWindow", u"\u526a\u5207", None))
#if QT_CONFIG(tooltip)
        self.editCut.setToolTip(QCoreApplication.translate("MainWindow", u"\u526a\u5207\u9009\u4e2d\u7684\u6587\u672c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.editCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.editCopy.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236", None))
#if QT_CONFIG(tooltip)
        self.editCopy.setToolTip(QCoreApplication.translate("MainWindow", u"\u590d\u5236\u9009\u4e2d\u7684\u6587\u672c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.editCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.editPaste.setText(QCoreApplication.translate("MainWindow", u"\u7c98\u8d34", None))
#if QT_CONFIG(tooltip)
        self.editPaste.setToolTip(QCoreApplication.translate("MainWindow", u"\u7c98\u8d34\u526a\u8d34\u677f\u4e2d\u7684\u6587\u672c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.editPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.editSelectAll.setText(QCoreApplication.translate("MainWindow", u"\u5168\u9009", None))
#if QT_CONFIG(tooltip)
        self.editSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u5168\u90e8\u6587\u672c", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.editSelectAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.editJumpToTop.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u6587\u9996", None))
#if QT_CONFIG(shortcut)
        self.editJumpToTop.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Home", None))
#endif // QT_CONFIG(shortcut)
        self.editJumpToSelection.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u6240\u9009\u5185\u5bb9", None))
#if QT_CONFIG(shortcut)
        self.editJumpToSelection.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.editJumpToBottom.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u6587\u672b", None))
#if QT_CONFIG(shortcut)
        self.editJumpToBottom.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+End", None))
#endif // QT_CONFIG(shortcut)
        self.editJumpToLineStart.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u884c\u9996", None))
        self.editJumpToLineEnd.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u884c\u672b", None))
        self.actionFind_and_Replace.setText(QCoreApplication.translate("MainWindow", u"Find and Replace", None))
        self.editFind.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e", None))
#if QT_CONFIG(shortcut)
        self.editFind.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.editFindNext.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u4e0b\u4e00\u4e2a", None))
#if QT_CONFIG(shortcut)
        self.editFindNext.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Right", None))
#endif // QT_CONFIG(shortcut)
        self.editFindPrevious.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u4e0a\u4e00\u4e2a", None))
#if QT_CONFIG(shortcut)
        self.editFindPrevious.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Left", None))
#endif // QT_CONFIG(shortcut)
        self.editReplace.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362", None))
#if QT_CONFIG(shortcut)
        self.editReplace.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.helpAbout.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.compileLaTeX.setText(QCoreApplication.translate("MainWindow", u"LaTeX/TeX", None))
        self.compileTypst.setText(QCoreApplication.translate("MainWindow", u"Typst", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6(&F)", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91(&E)", None))
#if QT_CONFIG(tooltip)
        self.menuSelection.setToolTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u5bf9\u6587\u672c\u7684\u64cd\u4f5c", None))
#endif // QT_CONFIG(tooltip)
        self.menuSelection.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.menuFindAndReplace.setTitle(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u548c\u66ff\u6362", None))
        self.menuCompile.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8bd1(&C)", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9(&H)", None))
    # retranslateUi

